version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: 3770853_db
      MYSQL_USER: 3770853_db
      MYSQL_PASSWORD: tucano2016
    ports:
      - "3306:3306"
  web:
    image: php-clinica
    container_name: php
    depends_on:
      - db
    ports:
      - "9000:9000"
    command: php -S 0.0.0.0:9000 -t /var/www/html
    volumes:
      - .:/var/www/html/
